drop table if exists USERS;
drop table if exists LOCATIONS;
drop table if exists HOTELS;
drop table if exists ROOMS;
drop table if exists ROOM_TYPES;
drop table if exists RESERVATIONS;
create table USERS (
  ID int generated by default as identity not null,
  USERNAME varchar(255) not null,
  PASSWORD_HASH varchar(255) not null,
  FIRST_NAME varchar(255) not null,
  MIDDLE_NAME varchar(255),
  LAST_NAME varchar(255) not null,
  EMAIL varchar(255) not null,
  primary key (ID),
  unique (USERNAME)
);
create table LOCATIONS (
  ID int generated by default as identity not null,
  LOCATION_NAME varchar(255) not null,
  primary key (ID)
);
create table HOTELS (
  ID int generated by default as identity not null,
  HOTEL_NAME varchar(255),
  LOCATION_ID int not null,
  primary key (ID),
  foreign key (LOCATION_ID)
  references LOCATIONS (ID)
);
create table ROOM_TYPES (
  ID int generated by default as identity not null,
  TYPE_STR varchar(255) not null,
  primary key (ID)
);
create table ROOMS (
  ID int generated by default as identity not null,
  ROOM_NAME varchar(255),
  GUESTS int not null,
  ROOM_TYPE int not null,
  HOTEL_ID int not null,
  primary key (ID),
  foreign key (HOTEL_ID)
  references HOTELS (ID),
  foreign key (ROOM_TYPE)
  references ROOM_TYPES (ID)
);
create table RESERVATIONS (
  ID int generated by default as identity not null,
  START_DT date not null default SYSDATE,
  END_DT date not null,
  USER_ID int not null,
  ROOM_ID int not null,
  primary key (ID),
  foreign key (USER_ID)
  references USERS (ID),
  foreign key (ROOM_ID)
  references ROOMS (ID)
);
